import { COLORS } from './colors'

export const CATEGORIES = [
  { id: 'alimentacao', name: 'Alimentação', icon: 'fast-food' },
  { id: 'mercado', name: 'Mercado', icon: 'cart' },
  { id: 'transporte', name: 'Transporte', icon: 'car' },
  { id: 'entretenimento', name: 'Entretenimento', icon: 'film' },
  { id: 'contas', name: 'Contas', icon: 'receipt' },
  { id: 'saude', name: 'Saúde', icon: 'medical' },
  { id: 'educacao', name: 'Educação', icon: 'school' },
  { id: 'vestuario', name: 'Vestuário', icon: 'shirt' },
  { id: 'casa', name: 'Casa', icon: 'home' },
  { id: 'viagem', name: 'Viagem', icon: 'airplane' },
  { id: 'carro', name: 'Carro', icon: 'car-sport' },
  { id: 'presentes', name: 'Presentes', icon: 'gift' },
  { id: 'pets', name: 'Pets', icon: 'paw' },
  { id: 'esportes', name: 'Esportes', icon: 'basketball' },
  { id: 'beleza', name: 'Beleza', icon: 'cut' },
  { id: 'tecnologia', name: 'Tecnologia', icon: 'laptop' },
  { id: 'restaurante', name: 'Restaurante', icon: 'restaurant' },
  { id: 'cafe', name: 'Café', icon: 'cafe' },
  { id: 'cinema', name: 'Cinema', icon: 'film' },
  { id: 'musica', name: 'Música', icon: 'musical-notes' },
  { id: 'livros', name: 'Livros', icon: 'book' },
  { id: 'salario', name: 'Salário', icon: 'cash' },
  { id: 'freelance', name: 'Freelance', icon: 'briefcase' },
  { id: 'investimentos', name: 'Investimentos', icon: 'trending-up' },
  { id: 'premios', name: 'Prêmios', icon: 'trophy' },
  { id: 'reembolso', name: 'Reembolso', icon: 'refresh' },
  { id: 'vendas', name: 'Vendas', icon: 'card' },
  { id: 'outros', name: 'Outros', icon: 'ellipsis-horizontal' }
]

export const CATEGORY_ICONS = {
  Alimentação: 'fast-food',
  Mercado: 'cart',
  Transporte: 'car',
  Entretenimento: 'film',
  Contas: 'receipt',
  Saúde: 'medical',
  Educação: 'school',
  Vestuário: 'shirt',
  Casa: 'home',
  Viagem: 'airplane',
  Carro: 'car-sport',
  Presentes: 'gift',
  Pets: 'paw',
  Esportes: 'basketball',
  Beleza: 'cut',
  Tecnologia: 'laptop',
  Restaurante: 'restaurant',
  Café: 'cafe',
  Cinema: 'film',
  Música: 'musical-notes',
  Livros: 'book',
  Salário: 'cash',
  Freelance: 'briefcase',
  Investimentos: 'trending-up',
  Prêmios: 'trophy',
  Reembolso: 'refresh',
  Vendas: 'card',
  Outros: 'ellipsis-horizontal'
}

export const CATEGORY_COLORS = {
  Alimentação: COLORS.expense,
  Mercado: '#DC2626',
  Transporte: '#EA580C',
  Entretenimento: '#DB2777',
  Contas: '#7C3AED',
  Saúde: '#059669',
  Educação: '#2563EB',
  Vestuário: '#C026D3',
  Casa: '#CA8A04',
  Viagem: '#DC2626',
  Carro: '#57534E',
  Presentes: '#EC4899',
  Pets: '#F59E0B',
  Esportes: '#10B981',
  Beleza: '#EC4899',
  Tecnologia: '#3B82F6',
  Restaurante: '#EF4444',
  Café: '#92400E',
  Cinema: '#7C3AED',
  Música: '#6366F1',
  Livros: '#8B5CF6',
  Outros: '#6B7280',

  Salário: COLORS.income,
  Freelance: '#10B981',
  Investimentos: '#059669',
  Prêmios: '#F59E0B',
  Reembolso: '#3B82F6',
  Vendas: '#8B5CF6'
}

export const getCategoryColor = categoryName => {
  return CATEGORY_COLORS[categoryName] || COLORS.primary
}
